services:
  api:
    build:
      dockerfile: ./Dockerfile
    environment:
      PORT: 8081
      MONGO_URL: mongodb://root:example@mongo:27017/
      REDIS_URL: redis://default:default@redis:6379
      COUNT_QUERY_LIMIT: 10 # low query limit for testing rate limiter
    ports:
      - 8081:8081
    depends_on: [mongo, redis, auth-tyk]
    restart: on-failure
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongoseed:
    build:
      dockerfile: ./seed.Dockerfile
    depends_on: [mongo]
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: "--requirepass default"
    restart: always
  auth-tyk:
    image: tykio/tyk-gateway:v5.14.0
    depends_on: [redis]
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      TYK_GW_LISTENPORT: 8080
      TYK_GW_STORAGE_TYPE: redis
      TYK_GW_STORAGE_HOST: redis
      TYK_GW_STORAGE_USERNAME: default
      TYK_GW_STORAGE_PASSWORD: default
      TYK_GW_STORAGE_PORT: 6379
      TYK_GW_SECRET: "secret" # This is fine. It's just local
      TYK_GW_GLOBALSESSIONLIFETIME: 7200
      TYK_GW_LOGFORMAT: "json"
