package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"saxypandabear.github.com/digimonql/graph/model"
)

// Digimon is the resolver for the digimon field.
func (r *queryResolver) Digimon(ctx context.Context, id string) (*model.Digimon, error) {
	return r.Database.GetDigimonByID(ctx, id)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
