package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"saxypandabear.github.com/digimonql/graph/model"
)

// Digimon is the resolver for the digimon field.
func (r *queryResolver) Digimon(ctx context.Context, id string) (*model.Digimon, error) {
	// TODO: add a real database
	for i := 0; i < len(r.digimons); i++ {
		digi := r.digimons[i]
		if id == digi.ID {
			return digi, nil
		}
	}

	return nil, fmt.Errorf("Could not find Digimon with ID: %s", id)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
