"""
The main point of compexlity with digivolutions is that one digimon
can evolve into many different forms, and there are shared forms.
For example, both Piyomon and Coronamon (very different) are able
to digivolve into Birdramon in the Time Stranger game. And then
Birdramon can digivolve into different forms, e.g.: Garudamon and Parrotmon.
There's no programmatic way to derive these evolution chains, and the
official reference doesn't track it. The chains need to be written by hand,
and unlike something like Pokemon, the evolution chains are nonunique.

Starting with Digimon Story: Time Stranger as a reference point for canon.
"""

# track a digimon and the set of digimon that they can evolve into
next_evolutions = {
    "bubbmon": ["pyocomon", "tanemon", "mochimon"],
    "dodomon": ["dorimon", "wanyamon"],
    "kuramon": ["pagumon", "tsumemon"],
    "punimon": ["tunomon", "nyaromon"],
    "botamon": ["koromon", "wanyamon", "pinamon"],
    "poyomon": ["pukamon", "tokomon"],
    "choromon": ["capromon"],
    "tanemon": ["floramon", "funbeemon", "lalamon", "mushmon", "palmon", "alraumon", "goburimon", "picodevimon", "renamon"],
    "wanyamon": ["bakumon", "bearmon", "gaomon", "renamon", "ryudamon", "dorumon", "kudamon", "sunarizamon", "morphomon"],
    "mochimon": ["tentomon", "gottsumon", "wormmon", "tyumon", "huckmon", "hagurumon", "solarmon", "morphomon"],
    "pyocomon": ["piyomon", "hyokomon", "muchomon", "penmon", "falcomon", "hawkmon", "mushmon", "wormmon", "elecmon"],
    "tsumemon": ["gabumon_black", "shamamon", "dracumon", "keramon", "toyagumon_black", "tukaimon", "agumon-black", "picodevimon"],
    "pagumon": ["picodevimon", "gazimon", "impmon", "otamamon", "tyumon", "lopmon"],
    "dorimon": ["monodramon", "dorumon", "lopmon", "snowgoburimon"],
    "nyaromon": ["kudamon", "kudamon-2006", "plotmon", "huckmon", "lunamon", "renamon", "piyomon", "armadimon", "terriermon"],
    "algomon_lv1": ["algomon_lv2"],
    "algomon_lv2": ["algomon_lv3"],
    "algomon_lv3": ["algomon_lv4"],
    "algomon_lv4": ["algomon-ultimate"],
    "algomon-ultimate": ["algomon"],
    "omegamon": ["omegamon_merciful", "imperialdramonpaladinmode"],
    "imperialdramonfightermode": ["imperialdramonpaladinmode"],
    "lucemon": ["rucemonfalldownmode", "icedevimon", "pidmon", "wizarmon", "chrysalimon", "angemon", "devimon"],
    "rucemonfalldownmode": ["lucemonsatanmode", "seraphimon", "belialvamdemon"],
    "alphamon": ["alphamon:ouryuken"],
    "ouryumon": ["alphamon:ouryuken"],
    "tunomon": ["zubamon", "ryudamon", "gabumon", "elecmon", "goburimon", "v-mon", "psychemon", "gabumon_black", "gumdramon", "monodramon"],
    "koromon": ["dracomon", "kotemon", "agumon", "agumon-2006", "guilmon", "shoutmon", "betamon", "v-mon", "toyagumon", "huckmon"],
    "pukamon": ["gomamon", "shakomon", "ganimon", "kamemon", "gizamon", "v-mon", "gumdramon", "clearagumon", "snowgoburimon", "otamamon", "betamon", "sangomon"],
    "tokomon": ["coronamon", "terriermon", "patamon", "armadimon", "lucemon", "tukaimon", "huckmon", "piyomon", "falcomon", "hawkmon", "sistermonblanc"],
    "capromon": ["toyagumon", "kokuwamon", "solarmon", "hagurumon"],
    "floramon": ["sunflowmon", "kiwimon", "togemon", "woodmon", "vegimon", "akatorimon"],
    "penmon": ["peckmon", "buraimon", "aquilamon", "kiwimon", "akatorimon", "cockatrimon", "orcamon", "thunderbirmon", "swanmon", "tocanmon"],
    "wormmon": ["snimon", "dokugumon", "stingmon", "kuwagamon", "devimon", "icedevimon", "kabuterimon", "hudiemon", "waspmon", "nohemon", "gokimon"],
    "funbeemon": ["kabuterimon", "dokugumon", "waspmon", "flymon", "stingmon", "goldnumemon", "gardromon_gold", "togemon", "raptordramon"],
    "tentomon": ["kabuterimon", "snimon", "sunflowmon", "kuwagamon", "waspmon", "redvegimon", "woodmon", "bombernanimon", "stingmon", "gokimon"],
    "bearmon": ["leomon", "gryzmon", "mojyamon", "gaogamon", "blackgaogamon", "mikemon"],
    "coronamon": ["agnimon", "firamon", "birdramon", "baohuckmon", "growmon", "meramon"],
    "lalamon": ["revolmon", "sunflowmon", "togemon", "turuiemon", "tuchidarumon", "woodmon", "vegimon"],
    "gaomon": ["leomon", "gaogamon", "blackgaogamon", "turuiemon", "nanimon", "strikedramon", "garurumon", "togemon", "sangloupmon", "galgomon", "orgemon", "baboongamon"],
    "lopmon": ["leomon", "gryzmon", "minotaurmon", "turuiemon", "tuchidarumon", "wendimon", "wizarmon", "blacktailmon", "galgomon", "devimon"],
    "mushmon": ["flymon", "scumon", "nanimon", "woodmon", "chamblemon", "vegimon", "tuchidarumon", "sunflowmon", "boogiemon"],
    "gazimon": ["dorugamon", "baohuckmon", "dobermon", "gaogamon", "blackgaogamon", "sangloupmon", "blacktailmon", "nanimon", "chrysalimon", "leomon"],
    "hyokomon": ["birdramon", "peckmon", "buraimon", "dinohumon"],
    "muchomon": ["birdramon", "airdramon", "fugamon", "peckmon", "akatorimon", "diatrymon", "swanmon", "pteranomon", "flarelizamon"],
    "renamon": ["reppamon", "kyubimon", "sunflowmon", "lekismon", "leomon", "turuiemon", "woodmon", "garurumon", "blacktailmon"],
    "shamamon": ["witchmon", "minotaurmon", "fugamon", "musyamon", "vegimon", "kuwagamon", "sorcerimon"],
    "lunamon": ["lekismon", "hyougamon", "garurumon", "yukidarumon", "sorcerimon", "icemon", "sangloupmon", "tailmon", "sistermon_ciel"],
    "solarmon": ["starmon", "meramon", "goldnumemon", "gardromon_gold", "birdramon", "redvegimon", "clockmon", "golemon", "geremon"],
    "gabumon_black": ["dobermon", "dorugamon", "blacktailmon", "fugamon", "minotaurmon", "garurumon_black", "stingmon", "garurumon", "saberdramon", "yukidarumon", "reppamon", "raremon", "vegimon"],
    "piyomon": ["yunimon", "wizarmon", "birdramon", "aquilamon", "pidmon", "youkomon", "kyubimon", "kabuterimon", "airdramon", "akatorimon"],
    "dracumon": ["starmon", "sangloupmon", "scumon", "wizarmon", "devimon", "raremon", "sistermon_ciel"],
    "picodevimon": ["greymon_blue", "devimon", "bakemon", "icedevimon", "orgemon", "blacktailmon", "chrysalimon", "kyubimon", "boogiemon"],
    "elecmon": ["aegiomon", "yunimon", "seadramon", "kuwagamon", "gekomon", "scumon", "leomon", "garurumon", "garurumon_black", "geremon", "nanimon"],
    "gottsumon": ["starmon", "icemon", "monochromon", "guardromon", "tuchidarumon", "golemon", "nanimon", "orgemon", "tyranomon", "clockmon", "ankylomon", "tankmon", "mikemon"],
    "dorumon": ["airdramon", "dorugamon", "drimogemon", "raptordramon", "sangloupmon", "xv-mon", "cyclomon", "waspmon", "guardromon"],
    "snowgoburimon": ["hyougamon", "yukidarumon", "tailmon", "icemon", "icedevimon", "monochromon", "ikkakumon", "seadramon"],
    "bakumon": ["garurumon", "yunimon", "kyubimon", "bakemon", "meramon", "opossummon", "sagittarimon"],
    "impmon": ["clockmon", "wizarmon", "witchmon", "devimon", "sangloupmon", "bakemon", "icedevimon", "orgemon", "blacktailmon", "sorcerimon", "boogiemon"],
    "falcomon": ["peckmon", "ginryumon", "kiwimon", "aquilamon", "xv-mon", "stingmon", "nohemon"],
    "falcomon-2006": ["peckmon", "ginryumon", "kiwimon", "aquilamon", "xv-mon", "stingmon", "nohemon"],
    "plotmon": ["tailmon", "drimogemon", "dobermon", "v-dramon", "ikkakumon", "sangloupmon", "blacktailmon", "galgomon", "meicoomon", "reppamon", "yukidarumon", "sorcerimon", "baohuckmon", "mikemon", "igamon"],
    "tyumon": ["tailmon", "blacktailmon", "scumon", "gekomon", "geremon", "platinasukamon", "nanimon", "raremon", "dogmon"],
    "gabumon": ["garurumon", "ikkakumon", "drimogemon", "kyubimon", "geremon", "gabumon_kizuna", "garurumon_black", "gaogamon", "blackgaogamon", "seadramon", "yukidarumon", "dorugamon", "numemon", "wolfmon"],
    "agumon-black": ["greymon_blue", "coredramon_b", "strikedramon", "tuskmon", "devimon", "saberdramon", "growmon", "fugamon", "cyclomon", "tyranomon", "tankmon", "monochromon"],
    "betamon": ["seadramon", "coelamon", "tuskmon", "devimon", "numemon", "vegimon", "airdramon", "karatukinumemon", "gekomon"],
    "palmon": ["mojyamon", "togemon", "platinasukamon", "woodmon", "vegimon", "chrysalimon", "redvegimon", "sunflowmon", "kuwagamon", "tuchidarumon"],
    "otamamon": ["seadramon", "karatukinumemon", "gekomon", "numemon", "platinasukamon", "coelamon", "raremon"],
    "goburimon": ["deltamon", "golemon", "tuskmon", "wendimon", "orgemon", "nanimon", "woodmon", "gaogamon", "blackgaogamon", "growmon", "greymon_blue", "coredramon_g", "igamon"],
    "ryudamon": ["greymon", "greymon-first", "reppamon", "ginryumon", "coelamon", "monochromon", "raptordramon"],
    "guilmon": ["growmon", "greymon_blue", "tyranomon", "xv-mon", "geogreymon", "growmon_orange", "agnimon", "meramon"],
    "hawkmon": ["firamon", "shurimon", "holsmon", "aquilamon", "airdramon", "birdramon", "meramon", "peckmon"],
    "huckmon": ["tailmon", "greymon", "greymon-first", "geogreymon", "growmon", "baohuckmon", "xv-mon", "goldv-dramon", "leomon", "garurumon", "monochromon", "platinasukamon"],
    "zubamon": ["zubaeagermon", "buraimon", "musyamon", "tankmon", "gardromon_gold", "ankylomon", "ginryumon", "baohuckmon", "goldnumemon"],
    "agumon": ["greymon", "greymon-first", "geogreymon", "coredramon_g", "raptordramon", "numemon", "agumon_kizuna", "tyranomon", "meramon", "greymon_blue", "agnimon", "scumon"],
    "agumon-2006": ["greymon", "greymon-first", "geogreymon", "coredramon_g", "raptordramon", "numemon", "agumon_kizuna", "tyranomon", "meramon", "greymon_blue", "agnimon", "scumon"],
    "kotemon": ["coredramon_b", "revolmon", "turuiemon", "dinohumon", "musyamon", "kyukimon", "gladimon", "igamon"],
    "shoutmon": ["omegashoutmon", "zubaeagermon", "galgomon", "gardromon_gold", "growmon", "greymon-first", "bulkmon"],
    "kamemon": ["sorcerimon", "dinohumon", "shellmon", "gawappamon", "octmon", "karatukinumemon"],
    "dracomon": ["v-dramon", "coredramon_b", "coredramon_g", "tyranomon", "seadramon", "deltamon", "ginryumon"],
    "gomamon": ["yukidarumon", "ikkakumon", "hyougamon", "icedevimon", "mojyamon", "sorcerimon", "seadramon", "icemon", "strikedramon", "ankylomon", "orcamon"],
    "terriermon": ["mojyamon", "galgomon", "gawappamon", "lekismon", "rapidmon_gold", "ikkakumon", "angemon", "orgemon", "tailmon", "yunimon"],
    "ganimon": ["snimon", "coelamon", "octmon", "gawappamon", "shellmon", "raremon"],
    "v-mon": ["v-dramon", "xv-mon", "magnamon", "fladramon", "lighdramon", "meramon", "goldv-dramon", "strikedramon", "wolfmon", "sagittarimon"],
    "shakomon": ["shellmon", "coelamon", "karatukinumemon", "octmon", "raremon", "ikkakumon", "gekomon", "seadramon"],
    "kudamon": ["wolfmon", "airdramon", "reppamon", "angemon", "ginryumon", "sorcerimon", "peckmon", "goldnumemon"],
    "kudamon-2006": ["wolfmon", "airdramon", "reppamon", "angemon", "ginryumon", "sorcerimon", "peckmon", "goldnumemon"],
    "patamon": ["yunimon", "angemon", "centalmon", "pegasmon", "pidmon", "v-dramon", "growmon_orange", "xv-mon", "tailmon", "birdramon", "reppamon"],
    "kokuwamon": ["clockmon", "centalmon", "kuwagamon", "waspmon", "mechanorimon"],
    "monodramon": ["strikedramon", "chrysalimon", "cyclomon", "deltamon", "raptordramon", "dorugamon"],
    "gizamon": ["zubaeagermon", "ranamon", "flymon", "geremon", "cyclomon", "ankylomon"],
    "toyagumon": ["blimpmon", "galgomon", "tankmon", "revolmon", "raremon", "wizarmon", "growmon_orange", "gardromon_gold", "greymon-first", "guardromon", "clockmon", "starmon", "scumon"],
    "hagurumon": ["mechanorimon", "blimpmon", "tankmon", "guardromon", "goldv-dramon", "kuwagamon", "bombernanimon", "clockmon", "goldnumemon", "platinasukamon", "starmon"],
    "armadimon": ["golemon", "ankylomon", "sabmarimon", "digmon", "geremon", "cyclomon", "tankmon", "goldnumemon"],
    "togemon": ["lilimon", "pumpmon", "jyureimon", "mamemon", "ladydevimon", "machgaogamon"],
    "aegiomon": ["aegiochusmon", "aegiochusmon:blue", "aegiochusmon:dark", "aegiochusmon:green", "aegiochusmon_holly"],
    "leomon": ["flaremon", "loaderleomon", "grappuleomon", "panjyamon", "rapidmon", "insekimon", "grademon", "metalgreymon-v", "indaramon"],
    "sunflowmon": ["delumon", "lilimon", "pumpmon", "lilamon", "angewomon"],
    "gaogamon": ["darksuperstarmon", "machgaogamon", "saviorhuckmon", "weregarrumon", "grappuleomon"],
    "greymon_blue": ["megalogrowmon", "skullbaluchimon", "metalgreymon-web", "skullgreymon", "gigadramon", "triceramon", "knightmon", "doruguremon"],
    "hyougamon": ["panjyamon", "fantomon", "zudomon", "bluemeramon"],
    "woodmon": ["taomon", "pumpmon", "jyureimon", "okuwamon", "mamemon"],
    "kiwimon": ["delumon", "lilamon", "jyureimon", "sirenmon"],
    "buraimon": ["duramon", "butenmon", "garudamon"],
    "fugamon": ["volcamon", "garudamon", "skullsatamon", "blackmegalogrowmon", "machgaogamon"],
    "snimon": ["jewelbeemon", "fantomon", "archnemon", "okuwamon", "scorpiomon"],
    "flymon": ["jewelbeemon", "atlurkabuterimon", "okuwamon", "megadramon"],
    "dokugumon": ["atlurkabuterimon", "archnemon", "mummymon", "infermon", "majiramon"],
    "stingmon": ["dinobeemon", "paildramon", "jewelbeemon", "okuwamon", "vespamon", "atlurkabuterimon-blue", "atlurkabuterimon", "infermon"],
    "kabuterimon": ["atlurkabuterimon", "atlurkabuterimon-blue", "chimairamon", "lilamon", "cannonbeemon", "skullgreymon", "jyureimon", "kongoumon"],
    "aquilamon": ["yatagaramon_axcel", "yatagaramon", "garudamon", "silphymon", "parrotmon", "earov-dramon", "hippogriffomon"],
    "birdramon": ["garudamon", "flaremon", "parrotmon", "deathmeramon", "earov-dramon", "agnimon", "vritramon", "hippogriffomon", "tyilinmon", "yatagaramon_axcel", "yatagaramon"],
    "xv-mon": ["paildramon", "dinobeemon", "earov-dramon", "metaltyranomon", "garudamon", "holyangemon", "rizegreymon", "wingdramon"],
    "firamon": ["flaremon", "saviorhuckmon", "mistymon"],
    "baohuckmon": ["loaderleomon", "rizegreymon", "saviorhuckmon", "garummon"],
    "waspmon": ["rapidmon", "tankdramon", "cannonbeemon", "vespamon", "atlurkabuterimon", "okuwamon"],
    "gardromon_gold": ["duramon", "masterblimpmon", "cannonbeemon", "metalmamemon", "nanomon", "rapidmon_gold", "grademon", "magnamon", "andromon"],
    "tuchidarumon": ["andiramon_2", "delumon", "gerbemon", "insekimon", "pumpmon", "pandamon"],
    "turuiemon": ["andiramon_2", "machgaogamon", "matadrmon", "megadramon", "monzaemon", "cyberdramon", "makuramon"],
    "wendimon": ["andiramon_2", "andiramon", "deathmeramon", "archnemon", "mephismon"],
    "gryzmon": ["weregarrumon", "grappuleomon", "greatgryzmon"],
    "dorugamon": ["metalgreymon-web", "rizegreymon", "doruguremon", "greatgryzmon", "grademon", "tyilinmon"],
    "witchmon": ["angewomon", "ladydevimon", "lilimon", "bastemon"],
    "lekismon": ["grappuleomon", "weregarrumon", "crescemon", "andiramon_2", "machgaogamon"],
    "icedevimon": ["panjyamon", "crescemon", "ladydevimon", "enbarrmon", "gigadramon", "zudomon", "jyureimon", "dagomon"],
    "starmon": ["volcamon", "darksuperstarmon", "superstarmon", "mamemon", "starmons", "catchmamemon", "crescemon", "metalmamemon"],
    "kyubimon": ["taomon", "enbarrmon", "cerberumon", "bluemeramon", "monzaemon", "weregarrumon", "ladydevimon", "indaramon"],
    "sangloupmon": ["astamon", "weregarrumon", "vamdemon", "matadrmon", "garummon", "phelesmon"],
    "icemon": ["panjyamon", "crescemon", "insekimon", "mamemon", "zudomon"],
    "garurumon": ["weregarrumon", "chimairamon", "taomon", "bluemeramon", "grappuleomon", "machgaogamon", "blackmegalogrowmon", "weregarurumon_black", "zudomon", "doruguremon", "panjyamon"],
    "numemon": ["monzaemon", "etemon", "darksuperstarmon", "blackkingnumemon"],
    "dobermon": ["darksuperstarmon", "cerberumon", "mummymon", "matadrmon", "scorpiomon"],
    "minotaurmon": ["grappuleomon", "triceramon", "etemon"],
    "kuwagamon": ["chimairamon", "anomalocarimon", "okuwamon", "jyureimon", "metallifekuwagamon", "megalograwmon_orange", "infermon", "cannonbeemon"],
    "devimon": ["vamdemon", "ladydevimon", "skullsatamon", "astamon", "infermon", "doumon", "bluemeramon", "metalgreymon-web", "bastemon"],
    "gekomon": ["hangyomon", "sirenmon", "tonosamagekomon", "whamon", "megaseadramon"],
    "v-dramon": ["wingdramon", "metalgreymon-web", "earov-dramon", "cyberdramon", "megaseadramon", "machgaogamon", "megalogrowmon", "metaltyranomon"],
    "meramon": ["deathmeramon", "bluemeramon", "bigmamemon", "vamdemon", "garudamon", "volcamon", "mamemon", "panjyamon", "vritramon"],
    "peckmon": ["yatagaramon_axcel", "yatagaramon", "vamdemon", "tyilinmon", "andiramon_2", "picklemon"],
    "blacktailmon": ["pandamon", "ladydevimon", "skullbaluchimon", "weregarurumon_black", "meicrackmon", "andiramon_2", "cyberdramon", "knightmon", "betsumon"],
    "scumon": ["gerbemon", "monzaemon", "mamemon", "etemon", "greatkingscumon", "superstarmon", "vademon"],
    "bakemon": ["fantomon", "bluemeramon", "vamdemon", "enbarrmon", "pumpmon", "matadrmon", "ladydevimon", "giromon"],
    "ginryumon": ["hisyaryumon", "butenmon", "skullgreymon", "megaseadramon", "cannonbeemon"],
    "monochromon": ["mammon", "triceramon", "cerberumon", "skullgreymon", "metaltyranomon"],
    "drimogemon": ["triceramon", "brachiomon", "loaderleomon"],
    "tuskmon": ["digitamamon", "triceramon", "groundramon"],
    "vegimon": ["tonosamagekomon", "vademon", "gerbemon", "mamemon", "okuwamon", "etemon", "lilamon", "digitamamon", "atlurkabuterimon", "ajatarmon"],
    "platinasukamon": ["mamemon", "metalmamemon", "vademon", "greatkingscumon", "etemon", "catchmamemon"],
    "nanimon": ["etemon", "superstarmon", "volcamon", "mamemon", "doumon", "waruseadramon", "insekimon", "digitamamon"],
    "orgemon": ["mummymon", "skullsatamon", "digitamamon", "skullgreymon", "metaltyranomon", "waruseadramon", "weregarrumon", "deathmeramon"],
    "reppamon": ["angewomon", "tyilinmon", "doruguremon", "megaseadramon", "picklemon", "rapidmon"],
    "tailmon": ["nefertimon", "angewomon", "silphymon", "lilimon", "betsumon"],
    "tyranomon": ["metalgreymon-v", "ex-tyranomon", "groundramon", "metaltyranomon", "metalgreymon-web", "megalogrowmon", "megadramon", "mamemon"],
    "raptordramon": ["grademon", "tankdramon", "gigadramon", "duramon", "doruguremon"],
    "musyamon": ["grademon", "butenmon", "hisyaryumon"],
    "yunimon": ["holyangemon", "tyilinmon", "hippogriffomon", "picklemon", "indaramon"],
    "garurumon_black": ["pandamon", "skullsatamon", "weregarurumon_black", "doumon", "etemon", "bluemeramon", "machgaogamon"],
    "growmon": ["megalogrowmon", "groundramon", "doruguremon", "blackmegalogrowmon", "skullgreymon", "metalgreymon-v", "metaltyranomon", "gigadramon", "vritramon"],
    "coredramon_g": ["megalogrowmon", "groundramon", "skullgreymon", "triceramon"],
    "dinohumon": ["grademon", "knightmon", "shawujinmon", "mephismon"],
    "gawappamon": ["hangyomon", "shawujinmon", "tonosamagekomon"],
    "karatukinumemon": ["pandamon", "waruseadramon", "orochimon", "blackkingnumemon", "tonosamagekomon", "megaseadramon"],
    "zubaeagermon": ["grademon", "duramon", "knightmon", "megalogrowmon", "garummon", "fantomon"],
    "wizarmon": ["wisemon", "nanomon", "mistymon", "rucemonfalldownmode", "vamdemon", "holyangemon", "deathmeramon", "fantomon"],
    "yukidarumon": ["insekimon", "mammon", "panjyamon", "crescemon", "angewomon", "zudomon"],
    "golemon": ["insekimon", "mammon", "volcamon", "pumpmon", "banchogolemon"],
    "shellmon": ["whamon", "anomalocarimon", "picklemon", "marinbullmon"],
    "goldnumemon": ["blackkingnumemon", "vademon", "waruseadramon", "platinumnumemon"],
    "raremon": ["ex-tyranomon", "dagomon", "skullbaluchimon", "tonosamagekomon", "blackkingnumemon", "rareraremon", "fantomon", "skullsatamon", "metalgreymon-web"],
    "coredramon_b": ["gigadramon", "wingdramon", "earov-dramon", "bluemeramon"],
    "angemon": ["holyangemon", "hippogriffomon", "sirenmon", "shakkoumon", "taomon", "bluemeramon", "garudamon", "saviorhuckmon", "bastemon"],
    "deltamon": ["metalgreymon-v", "skullbaluchimon", "chimairamon", "orochimon", "sharkmon"],
    "centalmon": ["andromon", "nanomon", "rapidmon", "sagittarimon"],
    "galgomon": ["machgaogamon", "rapidmon", "catchmamemon", "metalmamemon", "rapidmon_gold", "andiramon_2", "megalogrowmon"],
    "greymon": ["metalgreymon-v", "skullgreymon", "megadramon", "chimairamon", "megalograwmon_orange", "metalgreymon-web"],
    "greymon-first": ["metalgreymon-v", "skullgreymon", "megadramon", "chimairamon", "megalograwmon_orange", "metalgreymon-web"],
    "octmon": ["hangyomon", "dagomon", "digitamamon"],
    "mojyamon": ["mammon", "zudomon", "picklemon", "mistymon"],
    "clockmon": ["andromon", "knightmon", "zudomon", "ex-tyranomon", "wisemon", "nanomon"],
    "geremon": ["monzaemon", "catchmamemon", "superstarmon", "etemon", "metalmamemon"],
    "revolmon": ["pandamon", "superstarmon", "wisemon"],
    "guardromon": ["andromon", "locomon", "catchmamemon", "nanomon", "metalmamemon", "metaltyranomon", "grappuleomon"],
    "strikedramon": ["locomon", "cyberdramon", "saviorhuckmon", "weregarrumon"],
    "cyclomon": ["grademon", "cyberdramon", "brachiomon", "doruguremon", "nanomon", "megadramon"],
    "geogreymon": ["metaltyranomon", "cyberdramon", "rizegreymon", "gigadramon", "groundramon", "skullgreymon"],
    "airdramon": ["earov-dramon", "megadramon", "gigadramon", "hisyaryumon", "wingdramon", "megaseadramon", "metalgreymon-v", "sandiramon"],
    "tankmon": ["bigmamemon", "locomon", "tankdramon", "andromon", "gigadramon", "cannonbeemon", "knightmon", "volcamon"],
    "mechanorimon": ["bigmamemon", "megadramon", "nanomon"],
    "blimpmon": ["locomon", "masterblimpmon", "metalmamemon", "giromon"],
    "ankylomon": ["brachiomon", "insekimon", "shakkoumon", "groundramon", "skullgreymon", "holyangemon"],
    "sorcerimon": ["holyangemon", "picklemon", "wisemon", "panjyamon", "bluemeramon", "andiramon_2"],
    "ikkakumon": ["whamon", "zudomon", "skullseadramon", "megaseadramon", "panjyamon", "rapidmon", "triceramon", "machgaogamon"],
    "seadramon": ["megaseadramon", "skullseadramon", "hisyaryumon", "whamon", "waruseadramon", "sharkmon", "gigadramon", "tonosamagekomon"],
    "coelamon": ["hangyomon", "waruseadramon", "skullseadramon", "metaltyranomon", "anomalocarimon", "andromon", "dagomon", "hisyaryumon", "megaseadramon"],
    "yatagaramon": ["valdurmon", "ravmon", "kuzuhamon", "minervamon", "ouryumon"],
    "yatagaramon_axcel": ["valdurmon", "ravmon", "kuzuhamon", "minervamon", "ouryumon"],
    "flaremon": ["apollomon", "blackwargreymon", "seraphimon"],
    "metalgreymon-web": ["blackwargreymon", "darkdramon", "cherubimon-vice", "alphamon", "boltmon", "gaioumon", "wargreymon"],
    "darksuperstarmon": ["ravmon", "titamon", "beelstarmon"],
    "lilimon": ["rosemon", "ceresmon", "sakuyamon", "lilithmon", "minervamon", "lotusmon", "holydramon", "bancholilimon", "bloomlordmon"],
    "paildramon": ["darkdramon", "imperialdramondragonmode", "dorugoramon", "ulforcevdramon", "magnamon"],
    "pumpmon": ["noblepumpmon", "rosemon", "lotusmon", "boltmon", "pinochimon"],
    "loaderleomon": ["chaosdramon", "metalgarurumon", "bancholeomon", "cresgarurumon", "zdgarurumon"],
    "aegiochusmon": ["jupitermon"],
    "aegiochusmon:blue": ["jupitermon"],
    "aegiochusmon:dark": ["chronomon_destroy"],
    "aegiochusmon:green": ["jupitermon"],
    "aegiochusmon_holly": ["jupitermon"],
    "duramon": ["wargreymon", "dukemon", "durandamon", "blitzgreymon", "victorygreymon", "jesmon", "tigervespamon"],
    "machgaogamon": ["miragegaogamon", "saintgalgomon", "metalgarurumon", "gankoomon", "justimon", "bancholeomon", "mercurymon"],
    "wingdramon": ["valdurmon", "shinegreymon", "slayerdramon", "ulforcevdramon", "dynasmon"],
    "volcamon": ["bancholeomon", "pilevolcamon", "apollomon", "gankoomon", "metaletemon"],
    "panjyamon": ["saberleomon", "miragegaogamon", "holydramon", "bancholeomon", "gankoomon"],
    "fantomon": ["ravmon", "piemon", "sakuyamon", "belphemonsleepmode", "titamon", "barbamon", "belialvamdemon"],
    "jyureimon": ["rosemon", "pinochimon", "grankuwagamon", "kuzuhamon"],
    "lilamon": ["rosemon", "pinochimon", "lilithmon", "lotusmon"],
    "weregarurumon_black": ["metalgarurumon_black", "pilevolcamon", "zdgarurumon", "duftmon", "minervamon", "miragegaogamon", "bancholeomon", "mercurymon"],
    "delumon": ["valdurmon", "ceresmon", "platinumnumemon"],
    "garudamon": ["hououmon", "griffomon", "jesmon", "holydramon", "justimon", "beelzebumon", "valdurmon", "ravmon"],
    "atlurkabuterimon": ["heraklekabuterimon", "tyrantkabuterimon", "chaosdukemon", "craniummon", "holydramon", "grankuwagamon"],
    "okuwamon": ["heraklekabuterimon", "tyrantkabuterimon", "grankuwagamon", "examon", "diablomon"],
    "archnemon": ["lotusmon", "lilithmon", "tyrantkabuterimon"],
    "jewelbeemon": ["heraklekabuterimon", "tigervespamon", "queenbeemon", "banchostingmon", "bloomlordmon"],
    "tankdramon": ["darkdramon", "gundramon", "ageisdramon", "brigadramon", "dukemon", "ouryumon", "seraphimon"],
    "dinobeemon": ["grankuwagamon", "tigervespamon", "imperialdramondragonmode"],
    "saviorhuckmon": ["gankoomon", "jesmon", "tigervespamon", "slayerdramon", "valkyrimon"],
    "astamon": ["beelzebumon", "plutomon", "belphemonsleepmode", "venomvamdemon"],
    "cannonbeemon": ["saintgalgomon", "tigervespamon", "queenbeemon", "grandlocomon"],
    "andiramon_2": ["dianamon", "cherubimon", "cherubimon-vice", "ofanimon", "belphemonsleepmode", "diablomon"],
    "parrotmon": ["hououmon", "crossmon"],
    "taomon": ["sakuyamon", "venusmon", "kuzuhamon", "dianamon", "barbamon", "arresterdramon", "gulfmon"],
    "skullgreymon": ["titamon", "skullmammon", "blackwargreymon", "craniummon", "shinegreymon", "demon"],
    "greatgryzmon": ["cherubimon-vice", "callismon"],
    "cerberumon": ["metalgarurumon_black", "saberleomon", "plutomon", "zdgarurumon", "diarbbitmon"],
    "cerberumon_werewolfmode": ["metalgarurumon_black", "saberleomon", "plutomon", "zdgarurumon", "diarbbitmon"],
    "silphymon": ["minervamon", "beelstarmon", "valkyrimon", "griffomon", "sakuyamon", "hououmon", "dynasmon"],
    "grappuleomon": ["bancholeomon", "marsmon", "duftmon", "saberleomon", "dynasmon", "saintgalgomon", "pilevolcamon"],
    "ladydevimon": ["mastemon", "beelstarmon", "lilithmon", "piemon", "kuzuhamon", "rosemon", "lotusmon"],
    "digitamamon": ["titamon", "bacchusmon", "minervamon", "belphemonsleepmode"],
    "weregarrumon": ["metalgarurumon", "mercurymon", "cresgarurumon", "zdgarurumon", "jijimon", "magnagarurumon", "duftmon", "miragegaogamon"],
    "deathmeramon": ["beelzebumon", "boltmon", "avengekidmon", "gankoomon"],
    "doruguremon": ["alphamon", "dorugoramon", "breakdramon", "sleipmon"],
    "crescemon": ["dianamon", "cherubimon", "lordknightmon", "sleipmon"],
    "ex-tyranomon": ["belphemonsleepmode", "cherubimon", "rusttyranomon"],
    "sirenmon": ["marinangemon", "ceresmon"],
    "monzaemon": ["callismon", "kingetemon", "platinumnumemon", "seraphimon", "vikemon", "minervamon", "sakuyamon", "saberleomon"],
    "etemon": ["pilevolcamon", "kingetemon", "metaletemon", "platinumnumemon", "saintgalgomon", "piemon"],
    "tonosamagekomon": ["bacchusmon", "kingetemon", "pukumon", "vikemon", "plesiomon", "leviamon"],
    "bluemeramon": ["marsmon", "pharaohmon", "leviamon", "gankoomon", "boltmon", "miragegaogamon", "darkdramon", "demon", "barbamon"],
    "tyilinmon": ["crossmon", "valkyrimon", "sleipmon", "seraphimon", "metalgarurumon"],
    "metalmamemon": ["metalgarurumon", "magnakidmon", "cresgarurumon", "zdgarurumon", "mugendramon", "magnagarurumon", "dynasmon", "princemamemon", "ebemon", "hiandromon"],
    "rizegreymon": ["shinegreymon", "sleipmon", "magnakidmon", "gaioumon", "slayerdramon"],
    "hisyaryumon": ["ouryumon", "gaioumon", "goddramon", "minervamon"],
    "triceramon": ["breakdramon", "ultimatebrakimon", "saberleomon", "grankuwagamon", "spinomon"],
    "metalgreymon-v": ["wargreymon", "blitzgreymon", "victorygreymon", "gaioumon", "shinegreymon", "alphamon", "rusttyranomon"],
    "vademon": ["avengekidmon", "ebemon", "heraklekabuterimon", "hiandromon"],
    "vamdemon": ["belialvamdemon", "venomvamdemon", "demon", "jijimon", "piemon", "barbamon", "granddracumon"],
    "gerbemon": ["jumbogamemon", "metaletemon"],
    "mummymon": ["hiandromon", "avengekidmon", "pharaohmon", "murmukusmon"],
    "nanomon": ["diablomon", "pharaohmon", "barbamon", "platinumnumemon", "metalgarurumon_black", "mugendramon", "grandlocomon", "deathmon"],
    "orochimon": ["minervamon", "bacchusmon", "gundramon"],
    "grademon": ["alphamon", "durandamon", "dynasmon", "ouryumon", "tigervespamon", "dorugoramon"],
    "hippogriffomon": ["crossmon", "dynasmon", "griffomon", "valdurmon", "seraphimon"],
    "pandamon": ["miragegaogamon", "justimon", "mercurymon", "kingetemon", "bancholeomon"],
    "groundramon": ["breakdramon", "megidramon", "vikemon"],
    "enbarrmon": ["skullmammon", "sleipmon", "craniummon_enbarrmon"],
    "shawujinmon": ["jumbogamemon", "pinochimon", "barbamon"],
    "megaseadramon": ["ouryumon", "metalseadramon", "jumbogamemon", "marinangemon", "leviamon", "mugendramon", "neptunemon", "plesiomon"],
    "mamemon": ["princemamemon", "pukumon", "sleipmon", "jijimon", "justimon", "platinumnumemon", "pinochimon", "wargreymon", "banchomamemon"],
    "mistymon": ["dynasmon", "medievaldukemon", "chaosdukemon", "zanbamon"],
    "skullsatamon": ["piemon", "ebemon", "barbamon", "granddracumon", "diablomon", "demon", "gulfmon"],
    "insekimon": ["boltmon", "metaletemon", "dianamon", "belphemonsleepmode", "cherubimon", "ebemon"],
    "anomalocarimon": ["vulcanusmon", "pukumon"],
    "picklemon": ["ofanimon", "venusmon", "clavisangemon", "marinangemon", "hououmon", "bloomlordmon"],
    "blackkingnumemon": ["metaletemon", "platinumnumemon", "princemamemon"],
    "gigadramon": ["gundramon", "chaosdramon", "mugendramon", "rusttyranomon", "justimon", "dynasmon", "grandlocomon", "darkdramon", "dorugoramon", "megidramon", "metalseadramon"],
    "knightmon": ["slashangemon", "duftmon", "zanbamon", "lordknightmon", "craniummon", "durandamon"],
    "skullbaluchimon": ["titamon_skullbaluchimon", "skullmammon"],
    "rapidmon": ["saintgalgomon", "hiandromon", "vikemon", "sleipmon", "magnagarurumon", "tigervespamon", "metalgarurumon_black"],
    "dagomon": ["vulcanusmon", "ebemon", "neptunemon", "leviamon", "parallelmon"],
    "superstarmon": ["goddramon", "justimon", "princemamemon", "gankoomon", "platinumnumemon"],
    "catchmamemon": ["metalgarurumon_black", "princemamemon", "platinumnumemon", "zdgarurumon", "justimon", "pinochimon"],
    "angewomon": ["holydramon", "mastemon", "ofanimon", "junomon", "lordknightmon", "marinangemon", "valkyrimon"],
    "andromon": ["craniummon", "hiandromon", "boltmon", "tigervespamon"],
    "matadrmon": ["slashangemon", "kuzuhamon", "granddracumon", "piemon", "belialvamdemon"],
    "cyberdramon": ["justimon", "ulforcevdramon", "alphamon"],
    "mammon": ["skullmammon", "vikemon"],
    "bigmamemon": ["princemamemon", "grandlocomon", "platinumnumemon"],
    "masterblimpmon": ["grandlocomon", "gundramon"],
    "shakkoumon": ["goddramon", "holydramon", "junomon", "vikemon", "chaosdukemon"],
    "zudomon": ["vikemon", "plesiomon", "metalseadramon", "boltmon", "titamon", "marinangemon", "metalgarurumon"],
    "brachiomon": ["rusttyranomon", "ultimatebrakimon", "ouryumon"],
    "holyangemon": ["slashangemon", "seraphimon", "clavisangemon", "goddramon", "cherubimon", "jesmon", "marinangemon", "valkyrimon", "lordknightmon", "shinegreymon", "murmukusmon"],
    "omegashoutmon": ["durandamon", "pilevolcamon", "magnakidmon", "shoutmondx", "shoutmon_ex6"],
    "shoutmondx": ["shoutmonx7"],
    "shoutmonx5": ["shoutmonx5b", "shoutmonx5s"],
    "megalogrowmon": ["megidramon", "chaosdramon", "dukemon", "chaosdukemon", "shinegreymon", "leviamon", "kaisergreymon", "darkdramon", "rusttyranomon"],
    "hangyomon": ["neptunemon", "plesiomon"],
    "whamon": ["marinangemon", "neptunemon", "plesiomon", "leviamon", "kingwhamon", "metalseadramon"],
    "butenmon": ["chronomon_holy", "chronomon_destroy", "griffomon", "gaioumon"],
    "earov-dramon": ["slayerdramon", "goddramon", "ulforcevdramon", "darkdramon", "jesmon", "omegashoutmon", "dynasmon", "ravmon"],
    "sharkmon": ["neptunemon", "metalseadramon"],
    "skullseadramon": ["metalseadramon", "leviamon"],
    "waruseadramon": ["metalseadramon", "megidramon", "leviamon", "demon", "metaletemon"],
    "megadramon": ["megidramon", "mugendramon", "arresterdramon", "darkdramon", "wargreymon", "belphemonsleepmode", "ulforcevdramon", "goddramon", "blackwargreymon", "ageisdramon", "dinorexmon", "huanglongmon", "plesiomon", "metalgarurumon", "examon", "dukemon"],
    "mugendramon": ["millenniumon", "armagemon"],
    "chimairamon": ["mugendramon", "millenniumon", "granddracumon"],
    "metaltyranomon": ["ultimatebrakimon", "mugendramon", "rusttyranomon", "wargreymon", "metalseadramon", "breakdramon", "blackwargreymon", "dukemon"],
    "wisemon": ["chaosdukemon", "demon", "ancientwisetmon", "belialvamdemon", "piemon", "belphemonsleepmode", "murmukusmon"],
    "locomon": ["hiandromon", "grandlocomon"],
    "valdurmon": ["chaosmonvaldurarm"],
    "dianamon": ["gracenovamon"],
    "apollomon": ["gracenovamon"],
    "bancholeomon": ["chaosmon", "chaosmonvaldurarm"],
    "darkdramon": ["chaosmon"],
    "minervamon": ["mervamon"],
    "metalgarurumon_black": ["omegamon_zwart"],
    "blackwargreymon": ["omegamon_zwart"],
    "titamon": ["titamon_skullbaluchimon"],
    "metalgarurumon": ["omegamon"],
    "wargreymon": ["omegamon"],
    "breakdramon": ["examon"],
    "slayerdramon": ["examon"],
    "craniummon": ["craniummon_enbarrmon"],
    "agnimon": ["aldamon", "dukemon", "hououmon", "shinegreymon", "kaisergreymon", "deathmeramon", "rizegreymon", "matadrmon"],
    "vritramon": ["aldamon", "kaisergreymon"],
    "wolfmon": ["beowolfmon", "knightmon", "weregarrumon"],
    "garummon": ["beowolfmon", "magnagarurumon"],
    "aldamon": ["kaisergreymon"],
    "beowolfmon": ["magnagarurumon"],
    "kaisergreymon": ["susanoomon"],
    "magnagarurumon": ["susanoomon"],
    "fairimon": ["jetsilphymon"],
    "shutumon": ["jetsilphymon"],
    "blitzmon": ["rhinokabuterimon"],
    "bolgmon": ["rhinokabuterimon"],
    "flamon": ["agnimon"],
    "storabimon": ["wolfmon"],
    "duskmon": ["raihimon"],
    "velgrmon": ["raihimon", "deathmon", "ancientsphinkmon", "gulfmon", "mametyramon", "dinotigermon", "metalfantomon", "stiffilmon"],
    "louwemon": ["raihimon"],
    "kaiserleomon": ["raihimon"],
    "chackmon": ["daipenmon"],
    "blizzarmon": ["daipenmon"],
    "cocomon": ["chocomon"],
    "chocomon": ["lopmon", "picodevimon", "shamamon", "toyagumon_black", "wormmon"],
    "jyarimon": ["gigimon"],
    "gigimon": ["guilmon", "goburimon", "solarmon", "gottsumon", "shoutmon"],
    "zerimon": ["gummymon"],
    "gummymon": ["terriermon", "clearagumon", "toyagumon", "hagurumon", "gaomon"],
    "chicomon": ["chibimon"],
    "chibimon": ["v-mon"],
    "sakumon": ["sakuttomon"],
    "sakuttomon": ["zubamon"],
    "zurumon": ["bubbmon"],
    "nyokimon": ["pyocomon"],
    "pafumon": ["kyaromon"],
    "kyaromon": ["kudamon", "kudamon-2006"],
    "pitchmon": ["pukamon", "chapmon"],
    "petitmon": ["babydmon"],
    "babydmon": ["dracomon", "agumonhakase", "gumdramon", "huckmon", "otamamon"],
    "puttimon": ["cupimon"],
    "cupimon": ["plotmon"],
    "fufumon": ["kyokyomon"],
    "kyokyomon": ["ryudamon"],
    "pupumon": ["puroromon"],
    "puroromon": ["funbeemon"],
    "puwamon": ["pinamon"],
    "pinamon": ["falcomon", "falcomon-2006", "swimmon", "candmon", "kamemon", "mushmon", "elecmon"],
    "popomon": ["frimon"],
    "frimon": ["liollmon"],
    "liollmon": ["leomon", "madleomon"],
    "bommon": ["missimon"],
    "missimon": ["commandramon"],
    "commandramon": ["sealsdramon", "hi-commandramon"],
    "sealsdramon": ["cargodramon", "scorpiomon"],
    "hi-commandramon": ["cargodramon"],
    "cargodramon": ["brigadramon"],
    "mokumon": ["petimeramon"],
    "petimeramon": ["candmon"],
    "candmon": ["meramon"],
    "yukimibotamon": ["nyaromon"],
    "yuramon": ["tanemon", "budmon"],
    "leafmon": ["minomon"],
    "minomon": ["wormmon", "kunemon", "dokunemon"],
    "kunemon": ["flymon", "waspmon", "kuwagamon", "gokimon"],
    "dokunemon": ["flymon", "waspmon", "kuwagamon"],
    "relemon": ["pokomon"],
    "pokomon": ["renamon"],
    "tsubumon": ["upamon"],
    "upamon": ["armadimon", "swimmon", "gizamon", "patamon", "sangomon"],
    "chapmon": ["kamemon"],
    "budmon": ["lalamon"],
    "torikaraballmon": ["ebiburgamon", "burgamon"],
    "ebiburgamon": ["potamon"],
    "burgamon": ["burgamon_lv4"],
    "burgamon_lv4": ["jyagamon"],
    "potamon": ["jyagamon"],
    "elecmon-violet": ["yunimon", "seadramon", "kuwagamon", "gekomon"],
    "otamamon-red": ["seadramon", "karatukinumemon", "gekomon", "numemon", "platinasukamon"],
    "koemon": ["hookmon", "hanumon", "igamon"],
    "keramon": ["octmon", "mechanorimon", "dokugumon", "wendimon", "chrysalimon", "guardromon", "kabuterimon", "meicoomon", "bakemon", "platinasukamon"],
    "chrysalimon": ["archnemon", "orochimon", "infermon", "dagomon", "nanomon", "atlurkabuterimon-blue", "taomon", "cyberdramon"],
    "infermon": ["diablomon", "belialvamdemon", "cherubimon-vice", "demon", "parallelmon"],
    "diablomon": ["armagemon"],
    "psychemon": ["garurumon_black", "kyubimon", "bombernanimon", "galgomon", "opossummon"],
    "tukaimon": ["saberdramon", "devimon", "youkomon", "garurumon_black", "igamon"],
    "hookmon": ["captainhookmon", "andromon", "majiramon"],
    "tinkermon": ["petermon"],
    "petermon": ["captainhookmon"],
    "youkomon": ["doumon", "weregarurumon_black", "atlurkabuterimon-blue", "indaramon"],
    "alraumon": ["zassoumon", "vegimon", "redvegimon", "youkomon", "togemon", "stingmon"],
    "toyagumon_black": ["nanimon", "guardromon", "fugamon", "greymon_blue"],
    "clearagumon": ["gardromon_gold", "icedevimon", "hyougamon", "xv-mon"],
    "kekomon": ["kekkomon"],
    "kekkomon": ["gekkomon"],
    "gekkomon": ["armalizamon"],
    "armalizamon": ["monarchlizamon"],
    "cougarmon": ["murasamemon"],
    "hyemon": ["fangmon"],
    "fukamon": ["mococomon"],
    "mococomon": ["kakamon"],
    "tomorimon": ["onibimon"],
    "onibimon": ["gasamon", "hanimon", "renamon", "wankomon"],
    "chicchimon": ["hyokomon", "penmon", "muchomon"],
    "sunmon": ["coronamon"],
    "moonmon": ["lunamon"],
    "marinbullmon": ["ryugumon", "ariemon"],
    "ryugumon": ["ariemon"],
    "elizamon": ["dimetromon"],
    "dimetromon": ["lamiamon"],
    "lamiamon": ["medusamon"],
    "yolkmon": ["fluffymon"],
    "fluffymon": ["pteromon"],
    "pteromon": ["galemon"],
    "galemon": ["grandgalemon"],
    "grandgalemon": ["zephagamon"],
    "fusamon": ["bowmon"],
    "bowmon": ["loogamon"],
    "loogamon": ["loogarmon"],
    "loogarmon": ["soloogarmon", "helloogarmon"],
    "helloogarmon": ["fenriloogamon"],
    "soloogarmon": ["fenriloogamon"],
    "bemmon": ["snatchmon"],
    "snatchmon": ["destromon"],
    "destromon": ["ragnamon"],
    "landramon": ["proganomon"],
    "proganomon": ["pyramidimon", "magneticdramon"],
    "pristimon": ["wolvermon"],
    "wolvermon": ["bearcatmon"],
    "chiropmon": ["nightchiropmon"],
    "nightchiropmon": ["scourgechiropmon"],
    "espimon": ["hoverespimon"],
    "curimon": ["gurimon"],
    "gurimon": ["gammamon"],
    "gammamon": ["betelgammamon", "gulusgammamon", "kausgammamon", "wezengammamon"],
    "wezengammamon": ["ghilliedhumon", "canoweissmon", "fumamon", "regulusmon", "zanmetsumon", "tankdramon"],
    "kausgammamon": ["ghilliedhumon", "canoweissmon", "fumamon", "regulusmon", "zanmetsumon", "brachiomon"],
    "gulusgammamon": ["ghilliedhumon", "canoweissmon", "vamdemon", "fumamon", "regulusmon", "zanmetsumon"],
    "betelgammamon": ["canoweissmon", "ghilliedhumon", "brachiomon", "fumamon", "regulusmon", "zanmetsumon"],
    "pyonmon": ["bosamon"],
    "bosamon": ["angoramon"],
    "angoramon": ["symbareangoramon", "publimon"],
    "symbareangoramon": ["lamortmon"],
    "lamortmon": ["anubimon", "diarbbitmon", "marsmon", "plutomon"],
    "dokimon": ["bibimon"],
    "bibimon": ["pulsemon"],
    "pulsemon": ["bulkmon", "exermon", "namakemon", "shoutmonx4", "runnermon", "thunderballmon"],
    "bulkmon": ["boutmon", "climbmon", "divemon", "metallifekuwagamon", "omegashoutmon", "pistmon", "shootmon", "tempomon", "dorbickmon"],
    "pomumon": ["parasaurmon"],
    "parasaurmon": ["toropiamon", "lilimon", "ajatarmon"],
    "ajatarmon": ["spinomon", "bloomlordmon"],
    "puyomon": ["puyoyomon"],
    "puyoyomon": ["jellymon"],
    "jellymon": ["teslajellymon"],
    "teslajellymon": ["thetismon"],
    "jazamon": ["jazardmon"],
    "jazardmon": ["jazarichmon"],
    "jazarichmon": ["metallicdramon"],
    "eosmon_lv4": ["eosmon_lv5"],
    "eosmon_lv5": ["eosmon_lv6"],
    "bulucomon": ["paledramon"],
    "paledramon": ["cryspaledramon"],
    "cryspaledramon": ["hexeblaumon"],
    "meicoomon": ["meicrackmon", "ladydevimon", "angewomon"],
    "meicrackmon": ["rasielmon", "raguelmon", "mastemon", "ofanimon", "rosemon"],
    "raguelmon": ["ordinemon"],
    "ofanimon": ["ordinemon"],
    "cotsucomon": ["kakkinmon"],
    "kakkinmon": ["ludomon"],
    "ludomon": ["tialudomon"],
    "tialudomon": ["raijiludomon"],
    "raijiludomon": ["bryweludramon"],
    "bryweludramon": ["ragnaloardmon"],
    "durandamon": ["ragnaloardmon"],
    "jokermon": ["piemon"],
    "millenniumon": ["moonmillenniumon", "zeedmillenniumon"],
    "cresgarurumon": ["omegamon-alter-s"],
    "blitzgreymon": ["omegamon-alter-s"],
    "paunchessmon": ["knightchessmon_black"],
    "knightchessmon_black": ["rookchessmon"],
    "rookchessmon": ["queenchessmon"],
    "paunchessmon-white": ["knightchessmon"],
    "knightchessmon": ["bishopchessmon"],
    "bishopchessmon": ["kingchessmon"],
    "gumdramon": ["tailmon", "turuiemon", "v-dramon", "arresterdramon"],
    "bombernanimon": ["insekimon", "metalmamemon", "megadramon", "mephismon"],
    "pidmon": ["monzaemon", "angewomon", "insekimon", "giromon"],
    "saberdramon": ["megadramon", "waruseadramon", "ladydevimon"],
    "goldv-dramon": ["metalgreymon-v", "megaseadramon", "rapidmon_gold"],
    "growmon_orange": ["megalograwmon_orange", "metalgreymon-v", "blackmegalogrowmon"],
    "redvegimon": ["lilimon", "megalograwmon_orange", "atlurkabuterimon"],
    "atlurkabuterimon-blue": ["craniummon", "sleipmon", "grankuwagamon"],
    "megalograwmon_orange": ["wargreymon", "examon", "rusttyranomon"],
    "blackmegalogrowmon": ["gaioumon", "chaosdukemon", "darkdramon", "beelzebumon"],
    "rapidmon_gold": ["magnamon", "omegashoutmon", "heraklekabuterimon"],
    "doumon": ["lilithmon", "piemon", "metalgarurumon_black", "kuzuhamon", "gulfmon"],
    "piemon": ["armagemon"],
    "metalseadramon": ["armagemon"],
    "arkadimon": ["leomon", "chrysalimon"],
    "hudiemon": ["cannonbeemon", "lilimon", "lilamon"],
    "sistermonblanc": ["galgomon", "lekismon", "sistermon_ciel"],
    "sistermon_ciel": ["pandamon", "ladydevimon"],
    "abbadomon": ["abbadomoncore"],
    "negamon": ["abbadomon"],
    "boutmon": ["achillesmon", "kazuchimon", "shoutmondx", "shroudmon"],
    "exermon": ["divemon", "okuwamon", "pistmon", "shootmon", "tempomon"],
    "runnermon": ["climbmon", "divemon", "pistmon", "shootmon", "tempomon"],
    "thunderballmon": ["blackrapidmon", "bolgmon", "boutmon", "mametyramon", "giromon", "maildramon", "metallifekuwagamon", "superstarmon"],
    "climbmon": ["ancientbeatmon", "grankuwagamon", "shivamon", "tyrantkabuterimon", "shroudmon"],
    "divemon": ["shivamon", "shroudmon"],
    "pistmon": ["achillesmon", "kazuchimon"],
    "shootmon": ["achillesmon", "shivamon"],
    "tempomon": ["achillesmon", "kazuchimon"],
    "agumonhakase": ["greymon", "greymon-first", "greymon_blue", "bakemon", "devidramon", "wizarmon", "coredramon_g", "peckmon", "reppamon"],
    "orcamon": ["marindevimon", "mermaimon"],
    "swanmon": ["holyangemon", "makuramon", "sinduramon", "superstarmon"],
    "makuramon": ["cherubimon", "cherubimon-vice", "hiandromon", "marsmon", "piemon", "saintgalgomon", "beelzebumon"],
    "opossummon": ["makuramon", "mammon", "pajiramon", "sinduramon"],
    "labramon": ["baromon", "darcmon", "dogmon", "kyubimon", "dobermon", "tobucatmon", "siesamon", "leomon", "mantaraymon"],
    "paomon": ["xiaomon"],
    "xiaomon": ["labramon"],
    "darcmon": ["angewomon", "duramon", "wisemon", "picklemon"],
    "neamon": ["dogmon", "opossummon", "witchmon", "angemon", "gesomon", "gladimon", "manbomon"],
    "gladimon": ["darkknightmon", "mametyramon", "knightmon", "mummymon", "mistymon", "volcamon"],
    "dogmon": ["digitamamon", "cerberumon", "metalgreymon-web", "oleamon"],
    "oleamon": ["plutomon", "marsmon"],
    "publimon": ["oleamon", "digitamamon"],
    "nefertimon": ["bastemon", ],
    "mikemon": ["bastemon", "betsumon", "majiramon"],
    "devidramon": ["majiramon", "sandiramon"],
    "sagittarimon": ["sleipmon", "ulforcevdramon", "grappuleomon", "pajiramon", "sandiramon"],
    "indaramon": ["belialvamdemon", "beelzebumon", "murmukusmon", "parasimon"],
    "sephirothmon": ["murmukusmon", ],
    "phelesmon": ["murmukusmon", "belialvamdemon", "demon", "pharaohmon", "piemon", "granddracumon"],
    "boogiemon": ["phelesmon", "neodevimon", "deathmeramon", "mephismon", "warumonzaemon"],
    "evilmon": ["phelesmon", "mephismon"],
    "pucchiemon": ["phelesmon"],
    "pucchiemon-green": ["phelesmon"],
    "mephismon": ["demon", "grankuwagamon", "sakuyamon", "piemon", "metalseadramon", "marsmon", "gulfmon"],
    "giromon": ["deathmon"],
    "deathmon": ["deathmon-black"],
    "igamon": ["giromon", "mamemon", "picklemon", "shakkoumon", "kyukimon", "vademon"],
    "swimmon": ["igamon", "nohemon", "tyranomon", "tylomon", "tobiumon", "numemon", "coelamon", "whamon"],
    "sangomon": ["hookmon", "shellmon", "octmon", "seadramon", "tobiumon"],
    "darumamon": ["ariemon"],
    "gasamon": ["manekimon", "musyamon", "peckmon", "shellmon"],
    "hanimon": ["manekimon", "kokeshimon", "fugamon", "shellmon"],
    "manekimon": ["darumamon", ],
    "wankomon": ["kokeshimon", "musyamon", "siesamon"],
    "kokeshimon": ["karakurumon"],
    "karakurumon": ["kaguyamon"],
    "nohemon": ["andiramon_2", "jyagamon"],
    "jyagamon": ["ancientsphinkmon", "rosemon", "spinomon", "blastmon"],
    "gogmamon": ["blastmon", ],
    "tortamon": ["gogmamon", "scorpiomon"],
    "baboongamon": ["gogmamon"],
    "sunarizamon": ["baboongamon", "tortamon", "togemon", "landramon", "gokimon"],
    "goromon": ["sunarizamon"],
    "sunamon": ["goromon"],
    "morphomon": ["gokimon", "yunimon", "waspmon", "hudiemon"],
    "gokimon": ["archnemon", "dinobeemon", "okuwamon", "kongoumon", "pucchiemon", "pucchiemon-green", "vamdemon", "atlurkabuterimon-blue"],
    "kongoumon": ["banchostingmon", "bigmamemon", "grankuwagamon"]
}
