"""
The main point of compexlity with digivolutions is that one digimon
can evolve into many different forms, and there are shared forms.
For example, both Piyomon and Coronamon (very different) are able
to digivolve into Birdramon in the Time Stranger game. And then
Birdramon can digivolve into different forms, e.g.: Garudamon and Parrotmon.
There's no programmatic way to derive these evolution chains, and the
official reference doesn't track it. The chains need to be written by hand,
and unlike something like Pokemon, the evolution chains are nonunique.

Starting with Digimon Story: Time Stranger as a reference point for canon.
"""

# track a digimon and the set of digimon that they can evolve into
next_evolutions = {
    "bubbmon": ["pyocomon", "tanemon", "mochimon"],
    "dodomon": ["dorimon", "wanyamon"],
    "kuramon": ["pagumon", "tsumemon"],
    "punimon": ["tunomon", "nyaromon"],
    "botamon": ["koromon"],
    "poyomon": ["pukamon", "tokomon"],
    "choromon": ["capromon"],
    "tanemon": ["floramon", "funbeemon", "lalamon", "mushmon", "palmon", "alraumon", "goburimon", "picodevimon", "renamon"],
    "wanyamon": ["bakumon", "bearmon", "gaomon", "renamon"],
    "mochimon": ["tentomon", "gottsumon", "wormmon", "tyumon", "huckmon", "hagurumon"],
    "pyocomon": ["piyomon", "hyokomon", "muchomon", "penmon", "falcomon", "hawkmon"],
    "tsumemon": ["gabumon_black", "shamamon", "dracumon", "keramon", "toyagumon_black", "tukaimon"],
    "pagumon": ["picodevimon", "gazimon", "impmon", "otamamon"],
    "dorimon": ["monodramon", "dorumon", "lopmon", "snowgoburimon"],
    "nyaromon": ["kudamon", "kudamon-2006", "plotmon", "huckmon", "lunamon", "renamon", "piyomon"],
    "algomon_lv1": ["algomon_lv2"],
    "algomon_lv2": ["algomon_lv3"],
    "algomon_lv3": ["algomon_lv4"],
    "algomon_lv4": ["algomon-ultimate"],
    "algomon-ultimate": ["algomon"],
    "omegamon": ["omegamon_merciful", "imperialdramonpaladinmode"],
    "imperialdramonfightermode": ["imperialdramonpaladinmode"],
    "lucemon": ["rucemonfalldownmode", "icedevimon", "pidmon", "wizarmon", "chrysalimon"],
    "rucemonfalldownmode": ["lucemonsatanmode"],
    "alphamon": ["alphamon:ouryuken"],
    "ouryumon": ["alphamon:ouryuken"],
    "tunomon": ["zubamon", "ryudamon", "gabumon", "elecmon", "goburimon", "v-mon", "psychemon", "gabumon_black", "gumdramon"],
    "koromon": ["dracomon", "kotemon", "agumon", "agumon-2006", "guilmon", "shoutmon", "betamon", "v-mon", "toyagumon"],
    "pukamon": ["gomamon", "shakomon", "ganimon", "kamemon", "gizamon", "v-mon", "gumdramon", "clearagumon", "snowgoburimon"],
    "tokomon": ["coronamon", "terriermon", "patamon", "armadimon", "lucemon", "tukaimon", "huckmon", "piyomon"],
    "capromon": ["toyagumon", "kokuwamon", "solarmon", "hagurumon"],
    "floramon": ["sunflowmon", "kiwimon", "togemon", "woodmon", "vegimon"],
    "penmon": ["peckmon", "buraimon", "aquilamon", "kiwimon"],
    "wormmon": ["snimon", "dokugumon", "stingmon", "kuwagamon", "devimon"],
    "funbeemon": ["kabuterimon", "dokugumon", "waspmon", "flymon", "stingmon", "goldnumemon"],
    "tentomon": ["kabuterimon", "snimon", "sunflowmon", "kuwagamon", "waspmon", "redvegimon", "woodmon", "bombernanimon"],
    "bearmon": ["leomon", "gryzmon", "mojyamon", "gaogamon"],
    "coronamon": ["agnimon", "firamon", "birdramon", "baohuckmon", "growmon", "meramon"],
    "lalamon": ["revolmon", "sunflowmon", "togemon", "turuiemon", "tuchidarumon"],
    "gaomon": ["leomon", "gaogamon", "turuiemon", "nanimon", "strikedramon", "garurumon", "togemon"],
    "lopmon": ["leomon", "gryzmon", "minotaurmon", "turuiemon", "tuchidarumon", "wendimon", "wizarmon", "blacktailmon"],
    "mushmon": ["flymon", "scumon", "nanimon", "woodmon"],
    "gazimon": ["dorugamon", "baohuckmon", "dobermon", "gaogamon", "sangloupmon", "blacktailmon"],
    "hyokomon": ["birdramon", "peckmon", "buraimon", "dinohumon"],
    "muchomon": ["birdramon", "airdramon", "fugamon", "peckmon"],
    "renamon": ["reppamon", "kyubimon", "sunflowmon", "lekismon", "leomon", "turuiemon"],
    "shamamon": ["witchmon", "minotaurmon", "fugamon", "musyamon", "vegimon", "kuwagamon", "sorcerimon"],
    "lunamon": ["lekismon", "hyougamon", "garurumon", "yukidarumon", "sorcerimon", "icemon"],
    "solarmon": ["starmon", "meramon", "goldnumemon", "gardromon_gold", "birdramon", "redvegimon"],
    "gabumon_black": ["dobermon", "dorugamon", "blacktailmon", "fugamon", "minotaurmon", "garurumon_black", "stingmon", "garurumon", "saberdramon"],
    "piyomon": ["yunimon", "wizarmon", "birdramon", "aquilamon", "pidmon", "youkomon", ],
    "dracumon": ["starmon", "sangloupmon", "scumon", "wizarmon"],
    "picodevimon": ["greymon_blue", "devimon", "bakemon", "icedevimon", "orgemon", "blacktailmon", "chrysalimon"],
    "elecmon": ["aegiomon", "yunimon", "seadramon", "kuwagamon", "gekomon"],
    "gottsumon": ["starmon", "icemon", "monochromon", "guardromon", "tuchidarumon", "golemon", "nanimon", "orgemon", "tyranomon"],
    "dorumon": ["airdramon", "dorugamon", "drimogemon", "raptordramon", "sangloupmon", "xv-mon"],
    "snowgoburimon": ["hyougamon", "yukidarumon", "tailmon", "icemon", "icedevimon", "monochromon", "ikkakumon", "seadramon"],
    "bakumon": ["garurumon", "yunimon", "kyubimon", "bakemon", "meramon"],
    "impmon": ["clockmon", "wizarmon", "witchmon", "devimon", "sangloupmon", "bakemon"],
    "falcomon": ["peckmon", "ginryumon", "kiwimon"],
    "plotmon": ["tailmon", "drimogemon", "dobermon", "v-dramon", "ikkakumon", "sangloupmon", "blacktailmon", "galgomon", "meicoomon"],
    "tyumon": ["tailmon", "blacktailmon", "scumon", "gekomon", "geremon", "platinasukamon"],
    "gabumon": ["garurumon", "ikkakumon", "drimogemon", "kyubimon", "geremon", "gabumon_kizuna", "garurumon_black", "gaogamon", "seadramon"],
    "agumon-black": ["greymon_blue", "coredramon_b", "strikedramon", "tuskmon", "devimon"],
    "betamon": ["seadramon", "coelamon", "tuskmon", "devimon", "numemon", "vegimon"],
    "palmon": ["mojyamon", "togemon", "platinasukamon", "woodmon", "vegimon", "chrysalimon", "redvegimon"],
    "otamamon": ["seadramon", "karatukinumemon", "gekomon", "numemon", "platinasukamon"],
    "goburimon": ["deltamon", "golemon", "tuskmon", "wendimon", "orgemon", "nanimon", "woodmon", "gaogamon"],
    "ryudamon": ["greymon", "reppamon", "ginryumon", "coelamon", "monochromon"],
    "guilmon": ["growmon", "greymon_blue", "tyranomon", "xv-mon", "geogreymon", "growmon_orange"],
    "hawkmon": ["firamon", "shurimon", "holsmon", "aquilamon"],
    "huckmon": ["tailmon", "greymon", "geogreymon", "growmon", "baohuckmon", "xv-mon", "goldv-dramon", "leomon", "garurumon"],
    "zubamon": ["zubaeagermon", "buraimon", "musyamon", "tankmon", "gardromon_gold", "ankylomon"],
    "agumon": ["greymon", "geogreymon", "coredramon_g", "raptordramon", "numemon", "agumon_kizuna", "tyranomon", "meramon", "greymon_blue"],
    "agumon-2006": ["greymon", "geogreymon", "coredramon_g", "raptordramon", "numemon", "agumon_kizuna", "tyranomon", "meramon", "greymon_blue"],
    "kotemon": ["coredramon_b", "revolmon", "turuiemon", "dinohumon", "musyamon"],
    "shoutmon": ["omegashoutmon", "zubaeagermon", "galgomon", "gardromon_gold"],
    "kamemon": ["sorcerimon", "dinohumon", "shellmon", "gawappamon", "octmon", "karatukinumemon"],
    "dracomon": ["v-dramon", "coredramon_b", "coredramon_g", "tyranomon", "seadramon", "deltamon"],
    "gomamon": ["yukidarumon", "ikkakumon", "hyougamon", "icedevimon", "mojyamon", "sorcerimon", "seadramon", "icemon"],
    "terriermon": ["mojyamon", "galgomon", "gawappamon", "lekismon", "rapidmon_gold", "ikkakumon", "angemon", "orgemon"],
    "ganimon": ["snimon", "coelamon", "octmon", "gawappamon", "shellmon", "raremon"],
    "v-mon": ["v-dramon", "xv-mon", "magnamon", "fladramon", "lighdramon", "meramon", "goldv-dramon"],
    "shakomon": ["shellmon", "coelamon", "karatukinumemon", "octmon", "raremon"],
    "kudamon": ["wolfmon", "airdramon", "reppamon", "angemon", "ginryumon", "sorcerimon"],
    "kudamon-2006": ["wolfmon", "airdramon", "reppamon", "angemon", "ginryumon", "sorcerimon"],
    "patamon": ["yunimon", "angemon", "centalmon", "pegasmon", "pidmon", "v-dramon", "growmon_orange"],
    "kokuwamon": ["clockmon", "centalmon", "kuwagamon", "waspmon", "mechanorimon"],
    "monodramon": ["strikedramon", "chrysalimon", "cyclomon", "deltamon", "raptordramon"],
    "gizamon": ["zubaeagermon", "ranamon", "flymon", "geremon", "cyclomon", "ankylomon"],
    "toyagumon": ["blimpmon", "galgomon", "tankmon", "revolmon", "raremon", "wizarmon", "growmon_orange", "gardromon_gold", "greymon"],
    "hagurumon": ["mechanorimon", "blimpmon", "clockmon", "tankmon", "guardromon", "goldv-dramon", "kuwagamon", "bombernanimon"],
    "armadimon": ["golemon", "ankylomon", "sabmarimon", "digmon"],
    "togemon": ["lilimon", "pumpmon", "jyureimon"],
    "aegiomon": ["aegiochusmon", "aegiochusmon:blue", "aegiochusmon:dark", "aegiochusmon:green", "aegiochusmon_holly"],
    "leomon": ["flaremon", "loaderleomon", "grappuleomon", "panjyamon"],
    "sunflowmon": ["delumon", "lilimon", "pumpmon", "lilamon"],
    "gaogamon": ["darksuperstarmon", "machgaogamon", "saviorhuckmon"],
    "greymon_blue": ["megalogrowmon", "skullbaluchimon", "metalgreymon-web"],
    "hyougamon": ["panjyamon", "fantomon", "zudomon"],
    "woodmon": ["taomon", "pumpmon", "jyureimon"],
    "kiwimon": ["delumon", "lilamon", "jyureimon", "sirenmon"],
    "buraimon": ["duramon", "butenmon", "garudamon"],
    "fugamon": ["volcamon", "garudamon", "skullsatamon"],
    "snimon": ["jewelbeemon", "fantomon", "archnemon", "okuwamon"],
    "flymon": ["jewelbeemon", "atlurkabuterimon", "okuwamon", "megadramon"],
    "dokugumon": ["atlurkabuterimon", "archnemon", "mummymon", "infermon"],
    "stingmon": ["dinobeemon", "paildramon", "jewelbeemon", "okuwamon"],
    "kabuterimon": ["atlurkabuterimon", "chimairamon", "lilamon", "cannonbeemon"],
    "aquilamon": ["yatagaramon_axcel", "yatagaramon", "garudamon", "silphymon", "parrotmon"],
    "birdramon": ["garudamon", "flaremon", "parrotmon", "deathmeramon"],
    "xv-mon": ["paildramon", "dinobeemon", "rizegreymon"],
    "firamon": ["flaremon", "saviorhuckmon", "mistymon"],
    "baohuckmon": ["loaderleomon", "rizegreymon", "saviorhuckmon"],
    "waspmon": ["rapidmon", "tankdramon", "cannonbeemon"],
    "gardromon_gold": ["duramon", "masterblimpmon", "cannonbeemon"],
    "tuchidarumon": ["andiramon_2", "delumon", "gerbemon"],
    "turuiemon": ["andiramon_2", "machgaogamon", "matadrmon"],
    "wendimon": ["andiramon_2", "andiramon", "deathmeramon", "archnemon"],
    "gryzmon": ["weregarrumon", "grappuleomon", "greatgryzmon"],
    "dorugamon": ["metalgreymon-web", "rizegreymon", "doruguremon", "greatgryzmon"],
    "witchmon": ["angewomon", "ladydevimon", "lilimon"],
    "lekismon": ["grappuleomon", "weregarrumon", "crescemon"],
    "icedevimon": ["panjyamon", "crescemon", "ladydevimon", "enbarrmon"],
    "starmon": ["volcamon", "darksuperstarmon", "superstarmon", "mamemon", "starmons"],
    "kyubimon": ["taomon", "enbarrmon", "cerberumon", "bluemeramon"],
    "sangloupmon": ["astamon", "weregarrumon", "vamdemon", "matadrmon"],
    "icemon": ["panjyamon", "crescemon", "insekimon"],
    "garurumon": ["weregarrumon", "chimairamon", "taomon", "bluemeramon"],
    "numemon": ["monzaemon", "etemon", "darksuperstarmon"],
    "dobermon": ["darksuperstarmon", "cerberumon", "mummymon", "matadrmon"],
    "minotaurmon": ["grappuleomon", "triceramon", "etemon"],
    "kuwagamon": ["chimairamon", "anomalocarimon", "okuwamon", "jyureimon", "metallifekuwagamon"],
    "devimon": ["vamdemon", "ladydevimon", "skullsatamon", "astamon", "infermon"],
    "gekomon": ["hangyomon", "sirenmon", "tonosamagekomon"],
    "v-dramon": ["wingdramon", "metalgreymon-web", "earov-dramon", "cyberdramon"],
    "meramon": ["deathmeramon", "bluemeramon", "bigmamemon"],
    "peckmon": ["yatagaramon_axcel", "yatagaramon", "vamdemon", "tyilinmon"],
    "blacktailmon": ["pandamon", "ladydevimon", "skullbaluchimon", "weregarurumon_black"],
    "scumon": ["gerbemon", "monzaemon", "mamemon", "etemon"],
    "bakemon": ["fantomon", "bluemeramon", "vamdemon", "enbarrmon"],
    "ginryumon": ["hisyaryumon", "butenmon", "skullgreymon"],
    "monochromon": ["mammon", "triceramon", "cerberumon"],
    "drimogemon": ["triceramon", "brachiomon", "loaderleomon"],
    "tuskmon": ["digitamamon", "triceramon", "groundramon"],
    "vegimon": ["tonosamagekomon", "vademon", "gerbemon"],
    "platinasukamon": ["mamemon", "metalmamemon", "vademon"],
    "nanimon": ["etemon", "superstarmon", "volcamon", "mamemon"],
    "orgemon": ["mummymon", "skullsatamon", "digitamamon"],
    "reppamon": ["angewomon", "tyilinmon", "doruguremon", "megaseadramon"],
    "tailmon": ["nefertimon", "angewomon", "silphymon"],
    "tyranomon": ["metalgreymon-v", "ex-tyranomon", "groundramon", "metaltyranomon"],
    "raptordramon": ["grademon", "tankdramon", "gigadramon"],
    "musyamon": ["grademon", "butenmon", "hisyaryumon"],
    "yunimon": ["holyangemon", "tyilinmon", "hippogriffomon"],
    "garurumon_black": ["pandamon", "skullsatamon", "weregarurumon_black"],
    "growmon": ["megalogrowmon", "groundramon", "doruguremon"],
    "coredramon_g": ["megalogrowmon", "groundramon", "skullgreymon"],
    "dinohumon": ["grademon", "knightmon", "shawujinmon"],
    "gawappamon": ["hangyomon", "shawujinmon", "tonosamagekomon"],
    "karatukinumemon": ["pandamon", "waruseadramon", "orochimon", "blackkingnumemon"],
    "zubaeagermon": ["grademon", "duramon", "knightmon", "megalogrowmon"],
    "wizarmon": ["wisemon", "nanomon", "mistymon"],
    "yukidarumon": ["insekimon", "mammon", "panjyamon", "crescemon", "angewomon"],
    "golemon": ["insekimon", "mammon", "volcamon"],
    "shellmon": ["whamon", "anomalocarimon", "picklemon"],
    "goldnumemon": ["blackkingnumemon", "vademon", "waruseadramon"],
    "raremon": ["ex-tyranomon", "dagomon", "skullbaluchimon", "tonosamagekomon", "blackkingnumemon"],
    "coredramon_b": ["gigadramon", "earov-dramon", "wingdramon"],
    "angemon": ["holyangemon", "hippogriffomon", "sirenmon", "shakkoumon"],
    "deltamon": ["metalgreymon-v", "skullbaluchimon", "chimairamon", "orochimon", "sharkmon"],
    "centalmon": ["andromon", "nanomon", "rapidmon"],
    "galgomon": ["machgaogamon", "rapidmon", "catchmamemon"],
    "greymon": ["metalgreymon-v", "skullgreymon", "megadramon", "chimairamon"],
    "octmon": ["hangyomon", "dagomon", "digitamamon"],
    "mojyamon": ["mammon", "zudomon", "picklemon", "mistymon"],
    "clockmon": ["andromon", "knightmon", "zudomon", "ex-tyranomon"],
    "geremon": ["monzaemon", "catchmamemon", "superstarmon"],
    "revolmon": ["pandamon", "superstarmon", "wisemon"],
    "guardromon": ["andromon", "locomon", "catchmamemon"],
    "strikedramon": ["locomon", "cyberdramon", "saviorhuckmon"],
    "cyclomon": ["grademon", "cyberdramon", "brachiomon"],
    "geogreymon": ["metaltyranomon", "cyberdramon", "rizegreymon"],
    "airdramon": ["earov-dramon", "megadramon", "gigadramon", "hisyaryumon"],
    "tankmon": ["bigmamemon", "locomon", "tankdramon"],
    "mechanorimon": ["bigmamemon", "megadramon", "nanomon"],
    "blimpmon": ["locomon", "masterblimpmon", "metalmamemon"],
    "ankylomon": ["brachiomon", "insekimon", "shakkoumon"],
    "sorcerimon": ["holyangemon", "picklemon", "wisemon"],
    "ikkakumon": ["whamon", "zudomon", "skullseadramon", "megaseadramon"],
    "seadramon": ["megaseadramon", "skullseadramon", "hisyaryumon", "whamon", "waruseadramon", "sharkmon"],
    "coelamon": ["hangyomon", "waruseadramon", "skullseadramon", "metaltyranomon", "anomalocarimon"],
    "yatagaramon": ["valdurmon", "ravmon", "kuzuhamon"],
    "yatagaramon_axcel": ["valdurmon", "ravmon", "kuzuhamon"],
    "flaremon": ["apollomon", "blackwargreymon", "seraphimon"],
    "metalgreymon-web": ["blackwargreymon", "darkdramon", "cherubimon-vice"],
    "darksuperstarmon": ["ravmon", "titamon", "beelstarmon"],
    "lilimon": ["rosemon", "ceresmon"],
    "paildramon": ["darkdramon", "imperialdramondragonmode", "dorugoramon"],
    "pumpmon": ["noblepumpmon", "rosemon", "lotusmon"],
    "loaderleomon": ["chaosdramon", "metalgarurumon", "bancholeomon"],
    "aegiochusmon": ["jupitermon"],
    "aegiochusmon:blue": ["jupitermon"],
    "aegiochusmon:dark": ["chronomon_destroy"],
    "aegiochusmon:green": ["jupitermon"],
    "aegiochusmon_holly": ["jupitermon"],
    "duramon": ["wargreymon", "dukemon", "durandamon"],
    "machgaogamon": ["miragegaogamon", "saintgalgomon"],
    "wingdramon": ["valdurmon", "shinegreymon", "slayerdramon"],
    "volcamon": ["bancholeomon", "pilevolcamon", "apollomon", "gankoomon"],
    "panjyamon": ["saberleomon", "miragegaogamon"],
    "fantomon": ["ravmon", "piemon", "sakuyamon", "belphemonsleepmode"],
    "jyureimon": ["rosemon", "pinochimon", "grankuwagamon"],
    "lilamon": ["rosemon", "pinochimon", "lilithmon"],
    "weregarurumon_black": ["metalgarurumon_black", "pilevolcamon"],
    "delumon": ["valdurmon", "ceresmon", "platinumnumemon"],
    "garudamon": ["hououmon", "griffomon", "jesmon"],
    "atlurkabuterimon": ["heraklekabuterimon", "tyrantkabuterimon"],
    "okuwamon": ["heraklekabuterimon", "tyrantkabuterimon", "grankuwagamon"],
    "archnemon": ["lotusmon", "lilithmon", "tyrantkabuterimon"],
    "jewelbeemon": ["heraklekabuterimon", "tigervespamon"],
    "tankdramon": ["darkdramon", "gundramon"],
    "dinobeemon": ["grankuwagamon", "tigervespamon"],
    "saviorhuckmon": ["gankoomon", "jesmon", "tigervespamon"],
    "astamon": ["beelzebumon", "plutomon", "belphemonsleepmode", "venomvamdemon"],
    "cannonbeemon": ["saintgalgomon", "tigervespamon"],
    "andiramon_2": ["dianamon", "cherubimon", "cherubimon-vice"],
    "parrotmon": ["hououmon", "crossmon"],
    "taomon": ["sakuyamon", "venusmon", "kuzuhamon"],
    "skullgreymon": ["titamon", "skullmammon"],
    "greatgryzmon": ["cherubimon-vice", "callismon"],
    "cerberumon": ["metalgarurumon_black", "saberleomon", "plutomon"],
    "cerberumon_werewolfmode": ["metalgarurumon_black", "saberleomon", "plutomon"],
    "silphymon": ["minervamon", "beelstarmon", "valkyrimon"],
    "grappuleomon": ["bancholeomon", "marsmon", "duftmon", "saberleomon"],
    "ladydevimon": ["mastemon", "beelstarmon", "lilithmon"],
    "digitamamon": ["titamon", "bacchusmon"],
    "weregarrumon": ["metalgarurumon", "mercurymon"],
    "deathmeramon": ["beelzebumon", "boltmon", "avengekidmon"],
    "doruguremon": ["alphamon", "dorugoramon"],
    "crescemon": ["dianamon", "cherubimon", "lordknightmon"],
    "ex-tyranomon": ["belphemonsleepmode", "cherubimon", "rusttyranomon"],
    "sirenmon": ["marinangemon", "ceresmon"],
    "monzaemon": ["callismon", "kingetemon"],
    "etemon": ["pilevolcamon", "kingetemon", "metaletemon"],
    "tonosamagekomon": ["bacchusmon", "kingetemon", "pukumon"],
    "bluemeramon": ["marsmon", "pharaohmon"],
    "tyilinmon": ["crossmon", "valkyrimon", "sleipmon"],
    "metalmamemon": ["metalgarurumon", "magnakidmon"],
    "rizegreymon": ["shinegreymon", "sleipmon", "magnakidmon"],
    "hisyaryumon": ["ouryumon", "gaioumon"],
    "triceramon": ["breakdramon", "ultimatebrakimon"],
    "metalgreymon-v": ["wargreymon", "gaioumon"],
    "vademon": ["avengekidmon", "ebemon"],
    "vamdemon": ["belialvamdemon", "venomvamdemon", "demon"],
    "gerbemon": ["jumbogamemon", "metaletemon"],
    "mummymon": ["hiandromon", "avengekidmon", "pharaohmon"],
    "nanomon": ["diablomon", "pharaohmon"],
    "orochimon": ["minervamon", "bacchusmon", "gundramon"],
    "grademon": ["alphamon", "durandamon", "dynasmon"],
    "hippogriffomon": ["crossmon", "dynasmon", "griffomon"],
    "pandamon": ["miragegaogamon", "justimon", "mercurymon"],
    "groundramon": ["breakdramon", "megidramon"],
    "enbarrmon": ["skullmammon", "sleipmon", "craniummon_enbarrmon"],
    "shawujinmon": ["jumbogamemon", "pinochimon", "barbamon"],
    "megaseadramon": ["ouryumon", "metalseadramon", "jumbogamemon"],
    "mamemon": ["princemamemon", "pukumon"],
    "mistymon": ["dynasmon", "medievaldukemon", "chaosdukemon", "zanbamon"],
    "skullsatamon": ["piemon", "ebemon", "barbamon"],
    "insekimon": ["boltmon", "metaletemon"],
    "anomalocarimon": ["vulcanusmon", "pukumon"],
    "picklemon": ["ofanimon", "venusmon", "clavisangemon"],
    "blackkingnumemon": ["metaletemon", "platinumnumemon"],
    "gigadramon": ["gundramon", "chaosdramon"],
    "knightmon": ["slashangemon", "duftmon", "zanbamon", "lordknightmon"],
    "skullbaluchimon": ["titamon_skullbaluchimon", "skullmammon"],
    "rapidmon": ["saintgalgomon", "hiandromon"],
    "dagomon": ["vulcanusmon", "ebemon"],
    "superstarmon": ["goddramon", "justimon", "princemamemon"],
    "catchmamemon": ["metalgarurumon_black", "princemamemon", "platinumnumemon"],
    "angewomon": ["holydramon", "mastemon", "ofanimon", "junomon"],
    "andromon": ["craniummon", "hiandromon", "boltmon"],
    "matadrmon": ["slashangemon", "kuzuhamon", "granddracumon"],
    "cyberdramon": ["justimon", "ulforcevdramon"],
    "mammon": ["skullmammon", "vikemon"],
    "bigmamemon": ["princemamemon", "grandlocomon", "platinumnumemon"],
    "masterblimpmon": ["grandlocomon", "gundramon"],
    "shakkoumon": ["goddramon", "holydramon", "junomon", "vikemon"],
    "zudomon": ["vikemon", "plesiomon"],
    "brachiomon": ["rusttyranomon", "ultimatebrakimon", "ouryumon"],
    "holyangemon": ["slashangemon", "seraphimon", "clavisangemon", "goddramon"],
    "omegashoutmon": ["durandamon", "pilevolcamon", "magnakidmon", "shoutmondx", "shoutmon_ex6"],
    "shoutmondx": ["shoutmonx7"],
    "shoutmonx5": ["shoutmonx5b", "shoutmonx5s"],
    "megalogrowmon": ["megidramon", "chaosdramon", "dukemon", "chaosdukemon"],
    "hangyomon": ["neptunemon", "plesiomon"],
    "whamon": ["marinangemon", "neptunemon", "plesiomon", "leviamon"],
    "butenmon": ["chronomon_holy", "chronomon_destroy", "griffomon", "gaioumon"],
    "earov-dramon": ["slayerdramon", "goddramon", "ulforcevdramon"],
    "sharkmon": ["neptunemon", "metalseadramon"],
    "skullseadramon": ["metalseadramon", "leviamon"],
    "waruseadramon": ["metalseadramon", "megidramon", "leviamon"],
    "megadramon": ["megidramon", "mugendramon"],
    "mugendramon": ["millenniumon"],
    "chimairamon": ["mugendramon", "millenniumon", "granddracumon"],
    "metaltyranomon": ["ultimatebrakimon", "mugendramon", "rusttyranomon"],
    "wisemon": ["chaosdukemon", "demon", "ancientwisetmon"],
    "locomon": ["hiandromon", "grandlocomon"],
    "valdurmon": ["chaosmonvaldurarm"],
    "dianamon": ["gracenovamon"],
    "apollomon": ["gracenovamon"],
    "bancholeomon": ["chaosmon", "chaosmonvaldurarm"],
    "darkdramon": ["chaosmon"],
    "minervamon": ["mervamon"],
    "metalgarurumon_black": ["omegamon_zwart"],
    "blackwargreymon": ["omegamon_zwart"],
    "titamon": ["titamon_skullbaluchimon"],
    "metalgarurumon": ["omegamon"],
    "wargreymon": ["omegamon"],
    "breakdramon": ["examon"],
    "slayerdramon": ["examon"],
    "craniummon": ["craniummon_enbarrmon"],
    "agnimon": ["aldamon"],
    "vritramon": ["aldamon"],
    "wolfmon": ["beowolfmon"],
    "garummon": ["beowolfmon"],
    "aldamon": ["kaisergreymon"],
    "beowolfmon": ["magnagarurumon"],
    "kaisergreymon": ["susanoomon"],
    "magnagarurumon": ["susanoomon"],
    "fairimon": ["jetsilphymon"],
    "shutumon": ["jetsilphymon"],
    "blitzmon": ["rhinokabuterimon"],
    "bolgmon": ["rhinokabuterimon"],
    "flamon": ["agnimon"],
    "storabimon": ["wolfmon"],
    "duskmon": ["raihimon"],
    "velgrmon": ["raihimon"],
    "louwemon": ["raihimon"],
    "kaiserleomon": ["raihimon"],
    "chackmon": ["daipenmon"],
    "blizzarmon": ["daipenmon"],
    "cocomon": ["chocomon"],
    "chocomon": ["lopmon", "picodevimon", "shamamon", "toyagumon_black", "wormmon"],
    "jyarimon": ["gigimon"],
    "gigimon": ["guilmon", "goburimon", "solarmon", "gottsumon", "shoutmon"],
    "zerimon": ["gummymon"],
    "gummymon": ["terriermon", "clearagumon", "toyagumon", "hagurumon", "gaomon"],
    "chicomon": ["chibimon"],
    "chibimon": ["v-mon"],
    "sakumon": ["sakuttomon"],
    "sakuttomon": ["zubamon"],
    "zurumon": ["bubbmon"],
    "nyokimon": ["pyocomon"],
    "pafumon": ["kyaromon"],
    "kyaromon": ["kudamon", "kudamon-2006"],
    "pitchmon": ["pukamon", "chapmon"],
    "petitmon": ["babydmon"],
    "babydmon": ["dracomon"],
    "puttimon": ["cupimon"],
    "cupimon": ["plotmon"],
    "fufumon": ["kyokyomon"],
    "kyokyomon": ["ryudamon"],
    "pupumon": ["puroromon"],
    "puroromon": ["funbeemon"],
    "puwamon": ["pinamon"],
    "pinamon": ["falcomon", "falcomon-2006"],
    "falcomon-2006": ["peckmon", "ginryumon", "kiwimon"],
    "popomon": ["frimon"],
    "frimon": ["liollmon"],
    "liollmon": ["leomon", "madleomon"],
    "bommon": ["missimon"],
    "missimon": ["commandramon"],
    "commandramon": ["sealsdramon", "hi-commandramon"],
    "sealsdramon": ["cargodramon"],
    "hi-commandramon": ["cargodramon"],
    "cargodramon": ["brigadramon"],
    "mokumon": ["petimeramon"],
    "petimeramon": ["candmon"],
    "candmon": ["meramon"],
    "yukimibotamon": ["nyaromon"],
    "yuramon": ["tanemon", "budmon"],
    "leafmon": ["minomon"],
    "minomon": ["wormmon", "kunemon", "dokunemon"],
    "kunemon": ["flymon", "waspmon", "kuwagamon"],
    "dokunemon": ["flymon", "waspmon", "kuwagamon"],
    "relemon": ["pokomon"],
    "pokomon": ["renamon"],
    "tsubumon": ["upamon"],
    "upamon": ["armadimon"],
    "chapmon": ["kamemon"],
    "budmon": ["lalamon"],
    "torikaraballmon": ["ebiburgamon", "burgamon"],
    "ebiburgamon": ["potamon"],
    "burgamon": ["burgamon_lv4"],
    "potamon": ["jyagamon"],
    "elecmon-violet": ["yunimon", "seadramon", "kuwagamon", "gekomon"],
    "otamamon-red": ["seadramon", "karatukinumemon", "gekomon", "numemon", "platinasukamon"],
    "koemon": ["hookmon", "hanumon"],
    "keramon": ["octmon", "mechanorimon", "dokugumon", "wendimon", "chrysalimon", "guardromon", "kabuterimon", "meicoomon"],
    "chrysalimon": ["archnemon", "orochimon", "infermon", "dagomon"],
    "infermon": ["diablomon", "belialvamdemon", "cherubimon-vice"],
    "diablomon": ["armagemon"],
    "psychemon": ["garurumon_black", "kyubimon", "bombernanimon", "galgomon"],
    "tukaimon": ["saberdramon", "devimon", "youkomon", "garurumon_black"],
    "hookmon": ["captainhookmon", "andromon"],
    "tinkermon": ["petermon"],
    "petermon": ["captainhookmon"],
    "youkomon": ["doumon"],
    "alraumon": ["zassoumon", "vegimon", "redvegimon", "youkomon", "togemon", "stingmon"],
    "toyagumon_black": ["nanimon", "guardromon", "fugamon", "greymon_blue"],
    "clearagumon": ["gardromon_gold", "icedevimon", "hyougamon", "xv-mon"],
}
