# some digimon have modes that don't have " Mode" in the name
known_mode_variants = [
    "apollomon_whispered",
    "fenriloogamon_takemikazuchi",
    "sistermon_ciel_Awake",
    "sistermon_noir_Awake",
    "sistermon_blanc_Awake",
    "blacktailmon_uver",
    "omegamonzwart_d",
    "jesmongx",
    "shoutmon_king",
    "aegiochusmon:blue",
    "aegiochusmon:dark",
    "aegiochusmon:green",
    "aegiochusmon_holly"
]

# map digimon to their modes
digimon_modes = {
    "apollomon": ["apollomon_whispered"],
    "armamon": ["armamon_burstmode"],
    "chronomon_destroy": ["chronomon_holy"],
    "chronomon_holy": ["chronomon_destroy"],
    "nezhamon": ["nazhamon_crimson"],
    "takutoumon": ["takutoumon_wrath"],
    "fenriloogamon": ["fenriloogamon_takemikazuchi"],
    "huanglongmon": ["huanglongmon_ruin"],
    "shinegreymon": ["shinegreymonburstmode", "shinegreymon_ruin"],
    "imperialdramonfightermode_vi": ["imperialdramon_dragon_black"],
    "imperialdramon_dragon_black": ["imperialdramonfightermode_vi"],
    "imperialdramonfightermode": ["imperialdramondragonmode"],
    "imperialdramondragonmode": ["imperialdramonfightermode"],
    "jupitermon": ["jupitermmon_wrath"],
    "sistermon_ciel": ["sistermon_ciel_Awake"],
    "sistermonnoir": ["sistermon_noir_Awake"],
    "sistermonblanc": ["sistermon_blanc_Awake"],
    "blacktailmon": ["blacktailmon_uver"],
    "omegamon_zwart": ["omegamonzwart_d"],
    "shoutmonx7": ["shoutmonx7_superior"],
    "weregarrumon": ["waregarurumon_sagittarius"],
    "metalgreymon-v": ["metalgreymon_alter"],
    "eyesmon": ["eyesmon_scatter"],
    "arresterdramon": ["arresterdramon_superior"],
    "jesmon": ["jesmongx"],
    "rasenmon": ["rasenmon_f"],
    "ofanimon_x": ["ofanimonfdm_x"],
    "ofanimon": ["ofanimonfalldownmode"],
    "justimon": ["justimon_blitzarm", "justimon_criticalarm"],
    "justimon_blitzarm": ["justimon", "justimon_criticalarm"],
    "justimon_criticalarm": ["justimon_blitzarm", "justimon"],
    "kuzuhamon": ["kuzuhamon_miko"],
    "cerberumon": ["cerberumon_werewolfmode"],
    "cerberumon_werewolfmode": ["cerberumon"],
    "aegiochusmon": ["aegiochusmon:blue", "aegiochusmon:dark", "aegiochusmon:green", "aegiochusmon_holly"],
    "madleomon": ["madleomon:armedmode"],
    "meicrackmon": ["meicrackmon_v"],
    "skullknightmon": ["skullknightmonbigaxemode", "skullknightmoncavaliermode"],
    "rosemon": ["rosemonburstmode"],
    "ravmon": ["ravmonburstmode"],
    "lucemonlarva": ["lucemonsatanmode"],
    "lucemonsatanmode": ["lucemonlarva"],
    "miragegaogamon": ["miragegaogamon:burstmode"],
    "belphemonsleepmode": ["belphemonragemode"],
    "belphemonragemode": ["belphemonsleepmode"],
    "beelzebumon": ["beelzebumonblastmode"],
    "duftmon": ["duftmonleopardmode"],
    "duftmonleopardmode": ["duftmon"],
    "dukemon": ["dukemoncrimsonmode"],
    "sakuyamon": ["sakuyamon:mikomode"],
}
