// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Filter struct {
	Name        *string  `json:"name,omitempty"`
	Level       *string  `json:"level,omitempty"`
	Attribute   *string  `json:"attribute,omitempty"`
	Moves       []string `json:"moves,omitempty"`
	IsMode      *bool    `json:"isMode,omitempty"`
	IsXAntibody *bool    `json:"isXAntibody,omitempty"`
}

type Query struct {
}
